### ISSUE TITLE
Safari: default page goes to 404

### ISSUE THREAD

**Issue by dong77** [Loopring/loopr#85]
If you visit https://loopr.io from safari, it goes to 404 directly.

**Comment by dyfvicture** [comment]
The issue seems like "imports cannot currently be added while imports are loading."
my-app wants to import page-markets but page-markets has not loaded yet, modify `this._showPage404.bind(this)` to `null` it will display correctly in Safari

[https://github.com/Polymer/polymer/issues/4476](url)

my-app.html:

    _pageChanged(page){
        const resolvedPageUrl = this.resolveUrl('page-' + page + '.html');
        Polymer.importHref(
              resolvedPageUrl,
              null,
              this._showPage404.bind(this),
              true);
    }

**Comment by dong77** [comment]
revert lazy loading

**Comment by dong77** [comment]
https://github.com/Loopring/loopr/pull/88
